- name: Ensure required packages are installed
  sudo: yes
  apt: name={{item}} state=installed
  with_items:
    - postgresql
    - python-psycopg2

- name: Start postgres
  sudo: yes
  service: name=postgresql state=started

