- name: Ensure required packages are installed
  sudo: yes
  apt: name={{item}} state=installed
  with_items:
    - postgresql
    - python-psycopg2

- name: Ensure db is created
  remote_user: postgres
  postgresql_db: name=mazeserver

- name: Create user
  remote_user: postgres
  postgresql_user: name=mazeserveruser password=mazeserveruser db=mazeserver

